"""
CLI for checking and generating the Matterix OT-2 gym env.

Two subcommands:

- ``ot2-matterix-env check`` — run non-launching readiness checks and exit
  nonzero with ``--strict`` when anything is missing.
- ``ot2-matterix-env generate <dir>`` — write a complete Matterix task
  extension scaffold (``matterix_ot2_env.py`` registering the gym task,
  ``matterix_ot2_actions.py`` implementing the connector's action factory,
  ``__init__.py``, and a README) into a new directory the user installs into
  the Matterix Isaac Lab environment.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from .asset import MatterixAssetConfigurationError, OT2MatterixAssetConfig
from .env import EnvironmentValidation, MatterixEnvironmentError, validate_environment

_ENV_MODULE = '''"""Matterix OT-2 gym environment (generated by ot2-matterix-env).

Import this module inside the Matterix Isaac Lab python environment so that
``gym.make("Matterix-OT2-LiquidHandler-v1")`` resolves to the OT-2 task.
The OT-2 articulation and nested tip rack come from the accepted Matterix
integration branches.  Import fails closed until all identity pins, alignment
profiles, and the 96-child manifest binding are verified.
"""

from __future__ import annotations

import os
from pathlib import Path

import gymnasium as gym

from matterix.envs import MatterixBaseEnvCfg
from matterix.managers.semantics.primitive_semantics.ot2 import (
    IsTipAttachedCfg,
    Ot2TipAttachmentCfg,
)
from matterix_sm import WaitCfg
from isaaclab.utils import configclass

try:
    from matterix_assets.robots import OT2_CFG, apply_ot2_joint_alignment
    from matterix_assets.labware import OT2_TIP_RACK_CFG, make_ot2_tip_rack_with_tips_cfg
except ImportError:  # OT-2 asset not installed yet
    OT2_CFG = None
    apply_ot2_joint_alignment = None
    OT2_TIP_RACK_CFG = None
    make_ot2_tip_rack_with_tips_cfg = None


def _matterix_config_path():
    candidates = [
        os.environ.get("OT2_MATTERIX_CONFIG", ""),
        str(Path(__file__).resolve().parents[1] / "config" / "matterix_ot2.json"),
        "config/matterix_ot2.json",
    ]
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            return Path(candidate)
    raise FileNotFoundError(
        "OT-2 Matterix config not found; set OT2_MATTERIX_CONFIG to the pinned "
        "config/matterix_ot2.json containing verified joint alignment."
    )


def _aligned_ot2_cfg():
    """Apply verified joint and base-frame alignment to the OT-2 articulation."""
    if OT2_CFG is None or apply_ot2_joint_alignment is None:
        return None
    from unitelabs.opentrons_ot2.matterix.asset import OT2MatterixAssetConfig

    asset = OT2MatterixAssetConfig.from_file(_matterix_config_path())
    asset.validate_joint_alignment()
    asset.validate_reference_frame_alignment()
    world_from_base = asset.reference_frame_alignment.world_from_base
    cfg = OT2_CFG(pos=world_from_base.translation_m)
    cfg.init_state.rot = world_from_base.transform_orientation(cfg.init_state.rot)
    binding = asset.tip_rack_bindings[0]
    cfg.semantics = [
        IsTipAttachedCfg(default_tip_asset_name=binding.asset_name),
        Ot2TipAttachmentCfg(ee_sensor_name=binding.ee_sensor_name),
    ]
    return apply_ot2_joint_alignment(cfg, asset.joint_alignment)


def _tip_rack_cfgs():
    """Place accepted nested tip racks from connector deck coordinates."""
    if OT2_TIP_RACK_CFG is None or make_ot2_tip_rack_with_tips_cfg is None:
        return {}
    from unitelabs.opentrons_ot2.digital_twin.config import DigitalTwinConfig
    from unitelabs.opentrons_ot2.matterix.asset import OT2MatterixAssetConfig

    connector_candidates = [
        os.environ.get("OT2_CONNECTOR_CONFIG", ""),
        str(Path(__file__).resolve().parents[1] / "config" / "ot2_dt_config.json"),
        "config/ot2_dt_config.json",
    ]
    connector_path = next(
        (Path(candidate) for candidate in connector_candidates if candidate and Path(candidate).is_file()),
        None,
    )
    if connector_path is None:
        raise FileNotFoundError("OT-2 connector config not found; set OT2_CONNECTOR_CONFIG")
    connector = DigitalTwinConfig.from_file(connector_path)
    asset = OT2MatterixAssetConfig.from_file(_matterix_config_path())
    asset.validate_reference_frame_alignment()
    asset.validate_tip_rack_bindings(connector)
    world_from_deck = asset.reference_frame_alignment.world_from_deck
    result = {}
    for binding in asset.tip_rack_bindings:
        placement = connector.placement(binding.labware_id)
        position = asset.reference_frame_alignment.deck_point_mm_to_world_m(
            (placement.origin.x, placement.origin.y, placement.origin.z)
        )
        rack_cfg = OT2_TIP_RACK_CFG(pos=position)
        rack_cfg.rot = world_from_deck.rotation_wxyz
        cfg = make_ot2_tip_rack_with_tips_cfg()
        cfg.pos = position
        cfg.rot = world_from_deck.rotation_wxyz
        result[f"{binding.asset_name}_rack"] = rack_cfg
        result[binding.asset_name] = cfg
    return result


ALIGNED_OT2_CFG = _aligned_ot2_cfg()
TIP_RACK_CFGS = _tip_rack_cfgs()


def _as_sequence(value):
    """Normalize a generated action factory result into one flat workflow."""
    return value if isinstance(value, list) else [value]


def _pick_and_return_tip_workflow():
    """Build the native OT-2 A1 pickup, hold, return, and physics release demo."""
    from unitelabs.opentrons_ot2.matterix.actions import PickUpTipCfg, ReturnTipCfg

    from .matterix_ot2_actions import build_ot2_action_cfg

    from unitelabs.opentrons_ot2.matterix.asset import OT2MatterixAssetConfig

    binding = OT2MatterixAssetConfig.from_file(_matterix_config_path()).tip_rack_bindings[0]
    pickup = build_ot2_action_cfg(
        PickUpTipCfg(mount=binding.mount, labware_id=binding.labware_id, well="A1")
    )
    return_tip = build_ot2_action_cfg(
        ReturnTipCfg(mount=binding.mount, labware_id=binding.labware_id, well="A1")
    )
    return [*_as_sequence(pickup), WaitCfg(duration=1.0), *_as_sequence(return_tip)]


@configclass
class OT2LiquidHandlerEnvCfg(MatterixBaseEnvCfg):
    """OT-2 liquid-handling task (four physical X/Y/Z/A USD joints)."""

    env_spacing = 2.5
    episode_length_s = 120.0

    # Home and joint clips come from the same verified profile as translation.
    articulated_assets = {} if ALIGNED_OT2_CFG is None else {"ot2": ALIGNED_OT2_CFG}
    objects = TIP_RACK_CFGS

    workflows = {
        "move_home": [WaitCfg(duration=1.0)],
        "pick_and_return_tip": _pick_and_return_tip_workflow(),
    }


def register_ot2_task() -> None:
    """Register the OT-2 gym task id (idempotent)."""
    try:
        gym.spec("Matterix-OT2-LiquidHandler-v1")
    except Exception:
        gym.register(
            id="Matterix-OT2-LiquidHandler-v1",
            entry_point="matterix.envs:MatterixBaseEnv",
            kwargs={"env_cfg_entry_point": OT2LiquidHandlerEnvCfg},
            disable_env_checker=True,
        )


register_ot2_task()
'''

_ACTIONS_MODULE = '''"""Matterix OT-2 action factory (generated by ot2-matterix-env).

Exposes ``build_ot2_action_cfg(action)`` — the entry point imported by
``unitelabs.opentrons_ot2.matterix.runtime.load_action_factory``.  Runs inside
the Matterix Isaac Lab python environment (torch + matterix_sm installed).
"""

from __future__ import annotations

import os
from pathlib import Path

from matterix_sm import SemanticActionCfg, WaitCfg
from matterix_sm.robot_action_spaces import OT2_JOINT_ACTION_SPACE
from matterix_sm.semantic_info import SemanticInfo


def _load_connector():
    """Load the pinned OT-2 connector deck config used for well resolution."""
    from unitelabs.opentrons_ot2.digital_twin.config import DigitalTwinConfig

    candidates = [
        os.environ.get("OT2_CONNECTOR_CONFIG", ""),
        str(Path(__file__).resolve().parents[1] / "config" / "ot2_dt_config.json"),
        "config/ot2_dt_config.json",
    ]
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            return DigitalTwinConfig.from_file(candidate)
    raise FileNotFoundError(
        "OT-2 connector config not found; set OT2_CONNECTOR_CONFIG to the "
        "pinned config/ot2_dt_config.json used by the connector."
    )


def _load_asset(connector=None):
    """Load the pinned executable Matterix OT-2 integration contract."""
    from unitelabs.opentrons_ot2.matterix.asset import OT2MatterixAssetConfig

    candidates = [
        os.environ.get("OT2_MATTERIX_CONFIG", ""),
        str(Path(__file__).resolve().parents[1] / "config" / "matterix_ot2.json"),
        "config/matterix_ot2.json",
    ]
    for candidate in candidates:
        if candidate and Path(candidate).is_file():
            config = OT2MatterixAssetConfig.from_file(candidate)
            config.validate_joint_alignment()
            config.validate_reference_frame_alignment()
            config.validate_tip_rack_bindings(connector or _load_connector())
            return config
    raise FileNotFoundError(
        "OT-2 Matterix config not found; set OT2_MATTERIX_CONFIG to the pinned "
        "config/matterix_ot2.json containing verified joint alignment."
    )


def _joint_move_cfg(move) -> object:
    """Build the Matterix joint-space move config for one OT-2 move."""
    try:
        from matterix_sm.primitive_actions.move_to_joint_config import MoveToJointConfigCfg
    except ImportError as error:
        raise ImportError(
            "OT-2 joint-space moves require the Matterix MoveToJointConfig "
            "primitive (matterix_sm/primitive_actions/move_to_joint_config.py); "
            "see OT2_MATTERIX_PORT_PLAN.md."
        ) from error
    return MoveToJointConfigCfg(
        agent_assets=move.agent_assets,
        action_space_info=OT2_JOINT_ACTION_SPACE,
        target_joint_positions=move.target_joint_positions,
        joint_indices=move.joint_indices,
        position_threshold=move.position_threshold,
        settling_time=move.settling_time,
    )


def build_ot2_action_cfg(action):
    """Translate one connector OT-2 semantic action into matterix_sm configs.

    One connector action may map to multiple primitives (e.g. PickUpTip =
    move + tip-presence semantic).  A single config is returned for
    one-to-one translations, otherwise a list of configs is returned
    (StateMachine.set_action_sequence accepts both).
    """
    from unitelabs.opentrons_ot2.matterix.actions_runtime import (
        MatterixMoveToJointConfig,
        MatterixSemanticAction,
        MatterixWait,
        translate_action,
    )

    connector = _load_connector()
    asset = _load_asset(connector)
    translated = translate_action(
        action,
        connector=connector,
        alignment=asset.joint_alignment,
        agent_asset="ot2",
        tip_rack_bindings=asset.tip_rack_bindings,
    )

    configs = []
    for cfg in translated.configs:
        if isinstance(cfg, MatterixMoveToJointConfig):
            configs.append(_joint_move_cfg(cfg))
        elif isinstance(cfg, MatterixSemanticAction):
            configs.append(
                SemanticActionCfg(
                    semantics=[
                        SemanticInfo(
                            type=item.type,
                            asset_name=item.asset_name,
                            value=item.value,
                            additional_info=dict(item.additional_info),
                        )
                        for item in cfg.semantics
                    ]
                )
            )
        elif isinstance(cfg, MatterixWait):
            configs.append(WaitCfg(duration=cfg.duration))
        else:
            raise ValueError(f"Unsupported translated OT-2 config: {cfg!r}")
    if not configs:
        raise ValueError(f"OT-2 action translation produced no configs: {action!r}")
    return configs[0] if len(configs) == 1 else configs
'''


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    check = subparsers.add_parser("check", help="Run non-launching Matterix OT-2 readiness checks.")
    check.add_argument("--connector-config", default="config/ot2_dt_config.json")
    check.add_argument("--matterix-config", default="config/matterix_ot2.json")
    check.add_argument("--json", action="store_true", help="Emit a machine-readable report.")
    check.add_argument("--strict", action="store_true", help="Exit 1 when any check is missing.")

    generate = subparsers.add_parser("generate", help="Generate a Matterix OT-2 task extension scaffold.")
    generate.add_argument("directory", help="Target directory for the generated extension.")
    generate.add_argument("--matterix-config", default="config/matterix_ot2.json")
    generate.add_argument("--force", action="store_true", help="Overwrite existing files.")

    return parser


def _cmd_check(args: argparse.Namespace) -> int:
    try:
        validation: EnvironmentValidation = validate_environment(
            args.connector_config,
            args.matterix_config,
        )
    except MatterixEnvironmentError as error:
        sys.stderr.write(f"error: {error}\n")
        return 1
    payload = {
        "ready": validation.ready,
        "checks": [check.to_mapping() for check in validation.checks],
    }
    if args.json:
        sys.stdout.write(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    else:
        lines = [f"[{check.status}] {check.name}: {check.detail}" for check in validation.checks]
        lines += [f"  fix: {check.remedy}" for check in validation.checks if not check.ok and check.remedy]
        lines.append("Summary: ready" if validation.ready else "Summary: Matterix OT-2 env is not ready")
        sys.stdout.write("\n".join(lines) + "\n")
    return 0 if validation.ready or not args.strict else 1


def _cmd_generate(args: argparse.Namespace) -> int:
    target = Path(args.directory)
    try:
        asset = OT2MatterixAssetConfig.from_file(args.matterix_config)
    except MatterixAssetConfigurationError as error:
        sys.stderr.write(f"error: {error}\n")
        return 1

    files = {
        "matterix_ot2_env.py": _ENV_MODULE,
        "matterix_ot2_actions.py": _ACTIONS_MODULE,
        "__init__.py": "# Matterix OT-2 task extension (generated).\n",
        "README.md": (
            "# Matterix OT-2 task extension\n\n"
            f"Task id: `{asset.task_id}`\n\n"
            "Install this package into the Matterix Isaac Lab environment, then\n"
            "`import matterix_tasks` (or this module) before `gym.make(...)`.\n\n"
            "## Ubuntu verification\n\n"
            "```sh\n"
            'cd ~/matterix-internal && export MATTERIX_PATH="$PWD"\n'
            "git -C source/matterix_assets/data submodule update --init --remote\n"
            "./matterix.sh -p scripts/random_agent.py --task Matterix-OT2-LiquidHandler-v1 --num_envs 256 --headless\n"
            "./matterix.sh -p scripts/random_agent.py --task Matterix-OT2-LiquidHandler-v1 --num_envs 1024 --headless\n"
            "```\n\n"
            "## Action factory\n\n"
            "`matterix_ot2_actions.py` implements `build_ot2_action_cfg(action)`;\n"
            "point `OT2_CONNECTOR_CONFIG` at the pinned `config/ot2_dt_config.json`.\n"
        ),
    }
    try:
        target.mkdir(parents=True, exist_ok=True)
        for name, content in files.items():
            path = target / name
            if path.exists() and not args.force:
                sys.stderr.write(f"skip (exists, use --force): {path}\n")
                continue
            path.write_text(content, encoding="utf-8")
            sys.stdout.write(f"wrote {path}\n")
    except OSError as error:
        sys.stderr.write(f"error: {error}\n")
        return 1
    return 0


def main(argv: list[str] | None = None) -> int:
    """Dispatch the check/generate subcommands."""
    args = _parser().parse_args(argv)
    if args.command == "check":
        return _cmd_check(args)
    if args.command == "generate":
        return _cmd_generate(args)
    _parser().print_help(sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
