"""Resolve bridge calls from the packaged, hash-pinned SiLA contract artifact."""

from __future__ import annotations

import dataclasses
import json
import re
from importlib.resources import files

from ..digital_twin.contract import ContractMismatchError, ContractSnapshot, EndpointContract, FeatureContract
from .models import EndpointKind, ExecutionMode, OT2Command

_WORD_BOUNDARY = re.compile(r"(?:^|_)([a-zA-Z0-9])")


@dataclasses.dataclass(frozen=True)
class EndpointBinding:
    """gRPC and contract metadata for one endpoint."""

    package: str
    service: str
    endpoint: str
    endpoint_kind: EndpointKind
    execution_mode: ExecutionMode
    parameters: tuple[str, ...]

    @property
    def wire_method(self) -> str:
        """Return the gRPC method generated by SiLA."""
        if self.endpoint_kind is EndpointKind.PROPERTY:
            return f"Get_{self.endpoint}"
        return self.endpoint


class ContractRegistry:
    """Read endpoint packages and modes from the exact packaged contract."""

    def __init__(self, snapshot: ContractSnapshot) -> None:
        self.snapshot = snapshot

    @classmethod
    def packaged(cls) -> ContractRegistry:
        """Load the connector's shipped contract artifact."""
        resource = files("unitelabs.opentrons_ot2").joinpath("contracts").joinpath("ot2_dt_contract.json")
        return cls(ContractSnapshot.from_mapping(json.loads(resource.read_text(encoding="utf-8"))))

    def resolve(self, feature_identifier: str, endpoint: str, kind: EndpointKind) -> EndpointBinding:
        """Resolve one endpoint or fail closed when it is absent."""
        feature = self._feature(feature_identifier)
        candidates = feature.commands if kind is EndpointKind.COMMAND else feature.properties
        contract = next((item for item in candidates if item.identifier == endpoint), None)
        if contract is None:
            msg = f"Contract {self.snapshot.contract_id} has no {kind.value} {feature_identifier}.{endpoint}"
            raise ContractMismatchError(msg)
        originator, category, _identifier, version = feature.fqi.split("/")
        package = f"sila2.{originator}.{category}.{feature.identifier.lower()}.{version}"
        return EndpointBinding(
            package=package,
            service=feature.identifier,
            endpoint=endpoint,
            endpoint_kind=kind,
            execution_mode=ExecutionMode(contract.mode),
            parameters=contract.parameters,
        )

    def command(
        self,
        *,
        step_id: str,
        action: str,
        feature_identifier: str,
        endpoint: str,
        parameters: dict[str, object],
        kind: EndpointKind = EndpointKind.COMMAND,
        side_effecting: bool,
    ) -> OT2Command:
        """Construct an invocation only after validating its exact parameter contract."""
        binding = self.resolve(feature_identifier, endpoint, kind)
        actual = tuple(_parameter_identifier(name) for name in parameters)
        if actual != binding.parameters:
            msg = (
                f"{feature_identifier}.{endpoint} parameters {actual} do not match "
                f"contract parameters {binding.parameters}"
            )
            raise ContractMismatchError(msg)
        if kind is EndpointKind.PROPERTY and parameters:
            msg = f"Property {feature_identifier}.{endpoint} cannot receive parameters"
            raise ContractMismatchError(msg)
        if kind is EndpointKind.PROPERTY and side_effecting:
            msg = f"Property {feature_identifier}.{endpoint} cannot be side effecting"
            raise ContractMismatchError(msg)
        return OT2Command(
            step_id=step_id,
            action=action,
            feature_identifier=feature_identifier,
            endpoint=endpoint,
            parameters=parameters,
            endpoint_kind=kind,
            execution_mode=binding.execution_mode,
            side_effecting=side_effecting,
        )

    def binding_for(self, command: OT2Command) -> EndpointBinding:
        """Resolve and revalidate an existing bridge command before transport."""
        binding = self.resolve(command.feature_identifier, command.endpoint, command.endpoint_kind)
        if binding.execution_mode is not command.execution_mode:
            msg = (
                f"{command.feature_identifier}.{command.endpoint} mode {command.execution_mode.value} "
                f"does not match contract mode {binding.execution_mode.value}"
            )
            raise ContractMismatchError(msg)
        actual = tuple(_parameter_identifier(name) for name in command.parameters)
        if actual != binding.parameters:
            msg = (
                f"{command.feature_identifier}.{command.endpoint} parameters {actual} do not match "
                f"contract parameters {binding.parameters}"
            )
            raise ContractMismatchError(msg)
        return binding

    def _feature(self, identifier: str) -> FeatureContract:
        feature = next((item for item in self.snapshot.features if item.identifier == identifier), None)
        if feature is None:
            msg = f"Contract {self.snapshot.contract_id} has no feature {identifier}"
            raise ContractMismatchError(msg)
        return feature


def _parameter_identifier(name: str) -> str:
    """Apply the SiLA Python-name to FDL-Identifier convention."""
    return _WORD_BOUNDARY.sub(lambda match: match.group(1).upper(), name)


def endpoint_parameters(endpoint: EndpointContract) -> tuple[str, ...]:
    """Expose endpoint parameters for diagnostics without mutable contract objects."""
    return endpoint.parameters
