sonar.organization=accelerationconsortium
sonar.projectKey=AccelerationConsortium_opentrons-ot2
sonar.projectName=opentrons-ot2

sonar.sources=src
sonar.tests=tests
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
